### ISSUE TITLE
ImportError: cannot import name log - OpenStack Kilo

### ISSUE THREAD

**Issue by zbikmarc** [cybercom-finland/neutron_vmware_dvswitch#2]
I'm using OpenStack kilo and trying to configure DVS driver but I encountered an error while starting neutron-server

2015-05-06 13:29:34.302 62254 ERROR stevedore.extension [-] Could not load 'dvs': cannot import name log
2015-05-06 13:29:34.302 62254 ERROR stevedore.extension [-] cannot import name log
2015-05-06 13:29:34.302 62254 TRACE stevedore.extension Traceback (most recent call last):
2015-05-06 13:29:34.302 62254 TRACE stevedore.extension   File "/usr/lib/python2.7/site-packages/stevedore/extension.py", line 162, in _load_plugins
2015-05-06 13:29:34.302 62254 TRACE stevedore.extension     verify_requirements,
2015-05-06 13:29:34.302 62254 TRACE stevedore.extension   File "/usr/lib/python2.7/site-packages/stevedore/named.py", line 123, in _load_one_plugin
2015-05-06 13:29:34.302 62254 TRACE stevedore.extension     verify_requirements,
2015-05-06 13:29:34.302 62254 TRACE stevedore.extension   File "/usr/lib/python2.7/site-packages/stevedore/extension.py", line 185, in _load_one_plugin
2015-05-06 13:29:34.302 62254 TRACE stevedore.extension     plugin = ep.load(require=verify_requirements)
2015-05-06 13:29:34.302 62254 TRACE stevedore.extension   File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
2015-05-06 13:29:34.302 62254 TRACE stevedore.extension     entry = __import__(self.module_name, globals(),globals(), ['__name__'])
2015-05-06 13:29:34.302 62254 TRACE stevedore.extension   File "/usr/lib/python2.7/site-packages/neutron/plugins/ml2/drivers/dvs/mechanism_dvs.py", line 31, in <module>
2015-05-06 13:29:34.302 62254 TRACE stevedore.extension     from neutron.openstack.common import log as logging
2015-05-06 13:29:34.302 62254 TRACE stevedore.extension ImportError: cannot import name log

This line seems to be problem:
from neutron.openstack.common import log as logging

Changing it to:
from neutron.common import log as logging
does not work ;)

**Comment by zbikmarc** [comment]
```from oslo_log import log as logging``` should be used instead

**Comment by toddnni** [comment]
Thanks for the report and for the fix. Let's keep this open until the fix is in the repo. 

There are two things that needs to be handled first
1. we don't have kilo system installed yet
2. we have refactoring plans and we need to think whether we do it first or not

**Comment by toddnni** [comment]
Unfortunately we are not spending any more effort to the driver (see #6) and we are not going to make it work on kilo. However, I understood that you got it working already. If you are still using the driver please fork it and share the fix.
